### ISSUE TITLE
Streamline pdRaster input

### ISSUE THREAD

**Issue by bumbanian** [SPATIAL-Lab/isorig#11]
asn = pdRaster(r$isoscape.rescale$mean,r$isoscape.rescale$sd,unknown=un,mask=naMap)

Can pdRaster identify and unpackage mean and sd rasters from a rescaled isoscape made in the package? Seems like we should be able to provide only "r" as an argument and it can identify the correct objects within this.

**Comment by Demerara** [comment]
Resolved. See uploaded pdRaster_v4.
