### ISSUE TITLE
oddsRatio w/ mulitple rasters

### ISSUE THREAD

**Issue by bumbanian** [SPATIAL-Lab/isorig#16]
How does oddsRatio handle multiple assignment rasters? Input should be only a single assignment surface, unclear what happens if (for example) a rasterstack w/ multiple assignment surfaces is provided as an argument.

**Comment by Demerara** [comment]
oddsRatio can handle data class of RasterLayer (one layer), RasterBrick (multiple layers), RasterStack (multiple layers). It was confused with vague annotation. Now it is clear after changed the annotation.
