### ISSUE TITLE
calRaster fails

### ISSUE THREAD

**Issue by bumbanian** [SPATIAL-Lab/isorig#20]
also...this is after a complete uninstall/reinstall of the package, following the steps in your Rmarkdown document

> r = calRaster(known = d, isoscape = d2h_world, mask = naMap)
Error in calRaster(known = d, isoscape = d2h_world, mask = naMap) : 
  known should be a data.frame, see help page of rescale function

**Comment by bumbanian** [comment]
Please check all functions in the most recent version and make sure the input data objects work correctly.

**Comment by Demerara** [comment]
Fixed.
Please reinstall the package from Github.

**Comment by Demerara** [comment]
Here is the Rmarkdown file to test the package:
https://github.com/SPATIAL-Lab/isorig/tree/master/Rmarkdown
