### ISSUE TITLE
update format of SpatialPointsDataFrame object containing knowns

### ISSUE THREAD

**Issue by bumbanian** [SPATIAL-Lab/isorig#27]
current format is a SPDF with data frame containing Longitude, Latitude, and isotope value columns. In order to streamline and make the code more robust, we should require that this object includes a dataframe with only 1 column containing the isotope values. Including the Long and Lat values in the DF is redundant.

**Comment by bumbanian** [comment]
I updated the calRaster function to take a SPDF with a single column data frame. A check is imposed and error returned if more than one column is present

**Comment by Demerara** [comment]
Great!

**Comment by bumbanian** [comment]
Please check - are there any other functions that take the known SPDF? If so lets update them, too.

**Comment by bumbanian** [comment]
I updated QA to accept new SPDF format
