### ISSUE TITLE
add argument allowing priors in pdRaster

### ISSUE THREAD

**Issue by bumbanian** [SPATIAL-Lab/isorig#30]
user can provide a raster layer that contains prior probabilities. This would need to be same projection, resolution as the isoscape raster. If present the prior raster would be multiplied by the conditional probability before the values are normalized to sum to 1.

**Comment by Demerara** [comment]
In  the case of inputting multiple samples in pdRaster. If priors are provided. Is this just one prior for all the samples? Or One prior for each sample?

I think it depends on the samples and priors. If all the samples are the same species and the prior is for the species, one prior for all is enough. If the samples can be divided into multiple groups and each group has one prior, then multiple priors are needed. 

Am I understanding this correctly?

**Comment by bumbanian** [comment]
I think one per analysis. As you say, we can allow them to run them separately if there are multiple groups needed.

Gabe

**Comment by Demerara** [comment]
Done. Please see here:
https://github.com/SPATIAL-Lab/isorig/commit/6485e1129c96f5c4563c87f569b30d64165a46e6#diff-e1e1d3d40573127e9ee0480caf1283d6
